# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d22447c5686983e1da83ed30946a80cc3c1df5bc11c5dc31336af1c9e4471aee7b79c845ef1fde27f5f7cd07f27ec238cf388cdbadc3141e0ed2294b6e3984b1

test:
  secret_key_base: 432dd421ca9465c1b74b1db386ba94fb32f4f26f27eae72b40dbabd6814f63e3cd70676f68a5c932acf85b71e9ffbbe66082df1f15714bcca3ddbb46548d8a4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
